# Prometheus Configuration for Mental Health Platform
# Comprehensive monitoring with HIPAA compliance

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mentalhealth-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"
  - "recording_rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # Frontend application monitoring
  - job_name: 'frontend'
    static_configs:
      - targets: 
          - 'frontend:8080'
    metrics_path: /metrics
    scrape_interval: 30s

  # Backend API monitoring
  - job_name: 'backend-api'
    static_configs:
      - targets:
          - 'backend-1:3000'
          - 'backend-2:3000'
    metrics_path: /api/metrics
    scrape_interval: 10s
    params:
      format: ['prometheus']

  # WebSocket server monitoring
  - job_name: 'websocket'
    static_configs:
      - targets:
          - 'ws-1:3002'
          - 'ws-2:3002'
    metrics_path: /metrics
    scrape_interval: 10s

  # PostgreSQL monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://mentalhealth.app
          - https://api.mentalhealth.app/health
          - https://ws.mentalhealth.app/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Crisis response time monitoring
  - job_name: 'crisis-response'
    static_configs:
      - targets: ['backend-1:3000']
    metrics_path: /api/metrics/crisis
    scrape_interval: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'crisis_.*'
        action: keep

  # HIPAA compliance metrics
  - job_name: 'compliance'
    static_configs:
      - targets: ['compliance-monitor:9200']
    metrics_path: /metrics
    scrape_interval: 60s

# Service discovery for Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# Remote write configuration for long-term storage
remote_write:
  - url: "https://metrics.mentalhealth.app/api/v1/write"
    basic_auth:
      username: prometheus
      password_file: /etc/prometheus/remote_write_password
    write_relabel_configs:
      - source_labels: [__name__]
        regex: '(go|process)_.*'
        action: drop
    queue_config:
      capacity: 10000
      max_shards: 100
      min_shards: 1
      max_samples_per_send: 5000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

# Remote read configuration for federated queries
remote_read:
  - url: "https://metrics.mentalhealth.app/api/v1/read"
    basic_auth:
      username: prometheus
      password_file: /etc/prometheus/remote_read_password
    read_recent: true